Extract out the application setup section
transcom/mymove-docs pull request #268
Opened 2023-01-18 03:40 UTC by YanZ777

Took out most of the items so that the linking all works.
The rest of the application setup will be handled in a separate PR.

## Things I'd like for reviewers to specifically look out for
Are the heading numbers correct? e.g. h1, h2, etc. 
Are the links correct? 
Is the organization of the files good?

## Questions for reviewers  
Should I preclude the file headers with "Setup:"? I took it out from the original README because they're all in their own files now under the "Application Setup" tab.

2023-01-26 22:32 UTC, rogeruiz requested changes
❌ This PR needs changes ...

I'm requesting changes, but this is still very good @YanZ777. My changes are mostly on the order of the items in the Sidebar for this section. The Nix documents needed to be ordered in the correct steps. And the overall Application Setup section should be ordered from `base-setup` to `setup-manually` and then `setup-using-nix` being the last one. 

> Are the heading numbers correct? e.g. h1, h2, etc.

Yes the heading numbers look good for me. I'm looking at the files in `docs/about/application-setup/*.md` and matching them against the old order from `docs/about/Welcome.md`. Some of the descendent headings are incorrect, but I'm providing links to suggestions you can apply in GitHub or locally.

> Are the links correct?

None of the internal links are broken, after building the application.

> Is the organization of the files good?

Organization looks great. Awesome work on this.

2023-01-26 22:32 UTC, rogeruiz commented on docs/about/application-setup/setup-using-nix/add-or-update-packages.md
> +# Add or Update Packages
```suggestion
---
sidebar_position: 4
---
# Add or Update Packages
```

2023-01-26 22:32 UTC, rogeruiz commented on docs/about/application-setup/setup-using-nix/clean-up-local-environment.md
> +# Clean Up Local Environment
```suggestion
---
sidebar_position: 3
---

# Clean Up Local Environment
```

2023-01-26 22:32 UTC, rogeruiz commented on docs/about/application-setup/setup-using-nix/initial-setup.md
> +# Nix Initial Setup
```suggestion
---
sidebar_position: 1
---

# Nix Initial Setup
```

2023-01-26 22:32 UTC, rogeruiz commented on docs/about/application-setup/setup-using-nix/install-dependencies.md
> +# Install Dependencies
```suggestion
---
sidebar_position: 2
---

# Install Dependencies
```

2023-01-26 22:32 UTC, rogeruiz commented on docs/about/application-setup/setup-using-nix/README.md
> +sidebar_position: 1
```suggestion
sidebar_position: 3
```

Let's be explicit that the Nix guide is after the Manual guide here. The should not both have a `sidebar_position` of 1.

2023-01-26 22:32 UTC, rogeruiz commented on docs/about/application-setup/setup-manually/README.md
> +sidebar_position: 1
```suggestion
sidebar_position: 2
```

2023-02-02 19:30 UTC, kctruss approved these changes
My gosh, it's beautiful! 😭 😍

2023-02-07 00:05 UTC, rogeruiz approved these changes
lgtm 🌈

2023-02-07 00:06 UTC, merged